env:
  global:
    secure: Flm4NY+X1N0GbL7Q9ZFIrOF0/rEpDBrOoUM5NxoJxVAM5jsk62RVCS/noJEzYHM1n7fiKyTTXb7k+Jkc3rsJQLOIPK3oDpSHrLo/9fkyTtbcqi5LOXnWLwpCD1UxtPKzO7sFAIuEHkfTbO2L8Y1zmSGQ/Zw5iqFeGDljXnL7hCk=

install:
  - yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-lang-cyrillic

script: make

after_success: .utility/update-gh-pages.sh
